-- Tier 3 Phase 1A local historical match ingestion schema.
-- This file intentionally creates only the Phase 1A foundation tables.

CREATE TABLE IF NOT EXISTS seasons (
    season_id TEXT PRIMARY KEY,
    season_name TEXT NOT NULL,
    start_date DATE,
    end_date DATE,
    is_current BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_name_mapping (
    source TEXT NOT NULL,
    source_name TEXT NOT NULL,
    canonical_name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (source, source_name)
);

CREATE TABLE IF NOT EXISTS historical_matches (
    match_id SERIAL PRIMARY KEY,
    season_id TEXT NOT NULL REFERENCES seasons(season_id),
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'football_data',
    source_file TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (season_id, home_team, away_team),
    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_team <> away_team),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0)
);

CREATE TABLE IF NOT EXISTS historical_understat_xg (
    understat_match_id TEXT PRIMARY KEY,
    season_id TEXT NOT NULL REFERENCES seasons(season_id),
    match_date DATE NOT NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_xg FLOAT NOT NULL,
    away_xg FLOAT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    source TEXT NOT NULL DEFAULT 'understat',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (season_id, match_date, home_team, away_team),
    CHECK (home_team <> away_team),
    CHECK (home_xg >= 0),
    CHECK (away_xg >= 0),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0)
);

CREATE TABLE IF NOT EXISTS match_features_v3_base (
    match_id INTEGER PRIMARY KEY REFERENCES historical_matches(match_id),
    season_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    home_win INTEGER NOT NULL,
    is_draw INTEGER NOT NULL,
    away_win INTEGER NOT NULL,
    home_home_matches_last5 INTEGER NOT NULL,
    away_away_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last5 INTEGER NOT NULL,
    away_overall_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last10 INTEGER NOT NULL,
    away_overall_matches_last10 INTEGER NOT NULL,
    home_goals_scored_home_last5 FLOAT NULL,
    home_goals_conceded_home_last5 FLOAT NULL,
    home_clean_sheet_rate_home_last5 FLOAT NULL,
    away_goals_scored_away_last5 FLOAT NULL,
    away_goals_conceded_away_last5 FLOAT NULL,
    away_clean_sheet_rate_away_last5 FLOAT NULL,
    home_xg_home_last5 FLOAT NULL,
    home_xga_home_last5 FLOAT NULL,
    away_xg_away_last5 FLOAT NULL,
    away_xga_away_last5 FLOAT NULL,
    home_points_overall_last5 FLOAT NULL,
    away_points_overall_last5 FLOAT NULL,
    home_points_overall_last10 FLOAT NULL,
    away_points_overall_last10 FLOAT NULL,
    home_goal_diff_overall_last5 FLOAT NULL,
    away_goal_diff_overall_last5 FLOAT NULL,
    home_xg_overall_last5 FLOAT NULL,
    home_xga_overall_last5 FLOAT NULL,
    away_xg_overall_last5 FLOAT NULL,
    away_xga_overall_last5 FLOAT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS elo_ratings_v3 (
    match_id INTEGER PRIMARY KEY REFERENCES historical_matches(match_id),
    season_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    home_elo_before FLOAT NOT NULL,
    away_elo_before FLOAT NOT NULL,
    home_elo_after FLOAT NOT NULL,
    away_elo_after FLOAT NOT NULL,
    home_elo_delta FLOAT NOT NULL,
    away_elo_delta FLOAT NOT NULL,
    elo_diff_before FLOAT NOT NULL,
    elo_diff_home_adjusted FLOAT NOT NULL,
    expected_home_score FLOAT NOT NULL,
    expected_away_score FLOAT NOT NULL,
    actual_home_score FLOAT NOT NULL,
    actual_away_score FLOAT NOT NULL,
    k_factor FLOAT NOT NULL,
    home_advantage FLOAT NOT NULL,
    home_initialization TEXT NOT NULL,
    away_initialization TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (home_team <> away_team),
    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0),
    CHECK (expected_home_score >= 0 AND expected_home_score <= 1),
    CHECK (expected_away_score >= 0 AND expected_away_score <= 1),
    CHECK (actual_home_score IN (0, 0.5, 1)),
    CHECK (actual_away_score IN (0, 0.5, 1))
);

CREATE TABLE IF NOT EXISTS match_features_v3_elo (
    match_id INTEGER PRIMARY KEY REFERENCES historical_matches(match_id),
    season_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    home_win INTEGER NOT NULL,
    is_draw INTEGER NOT NULL,
    away_win INTEGER NOT NULL,
    home_home_matches_last5 INTEGER NOT NULL,
    away_away_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last5 INTEGER NOT NULL,
    away_overall_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last10 INTEGER NOT NULL,
    away_overall_matches_last10 INTEGER NOT NULL,
    home_goals_scored_home_last5 FLOAT NULL,
    home_goals_conceded_home_last5 FLOAT NULL,
    home_clean_sheet_rate_home_last5 FLOAT NULL,
    away_goals_scored_away_last5 FLOAT NULL,
    away_goals_conceded_away_last5 FLOAT NULL,
    away_clean_sheet_rate_away_last5 FLOAT NULL,
    home_xg_home_last5 FLOAT NULL,
    home_xga_home_last5 FLOAT NULL,
    away_xg_away_last5 FLOAT NULL,
    away_xga_away_last5 FLOAT NULL,
    home_points_overall_last5 FLOAT NULL,
    away_points_overall_last5 FLOAT NULL,
    home_points_overall_last10 FLOAT NULL,
    away_points_overall_last10 FLOAT NULL,
    home_goal_diff_overall_last5 FLOAT NULL,
    away_goal_diff_overall_last5 FLOAT NULL,
    home_xg_overall_last5 FLOAT NULL,
    home_xga_overall_last5 FLOAT NULL,
    away_xg_overall_last5 FLOAT NULL,
    away_xga_overall_last5 FLOAT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    home_elo_before FLOAT NOT NULL,
    away_elo_before FLOAT NOT NULL,
    elo_diff_before FLOAT NOT NULL,
    elo_diff_home_adjusted FLOAT NOT NULL,
    expected_home_score FLOAT NOT NULL,
    expected_away_score FLOAT NOT NULL,
    home_initialization TEXT NOT NULL,
    away_initialization TEXT NOT NULL,
    CHECK (home_team <> away_team),
    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0),
    CHECK (home_win IN (0, 1)),
    CHECK (is_draw IN (0, 1)),
    CHECK (away_win IN (0, 1)),
    CHECK (expected_home_score >= 0 AND expected_home_score <= 1),
    CHECK (expected_away_score >= 0 AND expected_away_score <= 1)
);

CREATE TABLE IF NOT EXISTS match_features_v3_style_experiment (
    match_id INTEGER PRIMARY KEY REFERENCES historical_matches(match_id),
    season_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    home_win INTEGER NOT NULL,
    is_draw INTEGER NOT NULL,
    away_win INTEGER NOT NULL,
    home_home_matches_last5 INTEGER NOT NULL,
    away_away_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last5 INTEGER NOT NULL,
    away_overall_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last10 INTEGER NOT NULL,
    away_overall_matches_last10 INTEGER NOT NULL,
    home_goals_scored_home_last5 FLOAT NULL,
    home_goals_conceded_home_last5 FLOAT NULL,
    home_clean_sheet_rate_home_last5 FLOAT NULL,
    away_goals_scored_away_last5 FLOAT NULL,
    away_goals_conceded_away_last5 FLOAT NULL,
    away_clean_sheet_rate_away_last5 FLOAT NULL,
    home_xg_home_last5 FLOAT NULL,
    home_xga_home_last5 FLOAT NULL,
    away_xg_away_last5 FLOAT NULL,
    away_xga_away_last5 FLOAT NULL,
    home_points_overall_last5 FLOAT NULL,
    away_points_overall_last5 FLOAT NULL,
    home_points_overall_last10 FLOAT NULL,
    away_points_overall_last10 FLOAT NULL,
    home_goal_diff_overall_last5 FLOAT NULL,
    away_goal_diff_overall_last5 FLOAT NULL,
    home_xg_overall_last5 FLOAT NULL,
    home_xga_overall_last5 FLOAT NULL,
    away_xg_overall_last5 FLOAT NULL,
    away_xga_overall_last5 FLOAT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    home_elo_before FLOAT NOT NULL,
    away_elo_before FLOAT NOT NULL,
    elo_diff_before FLOAT NOT NULL,
    elo_diff_home_adjusted FLOAT NOT NULL,
    expected_home_score FLOAT NOT NULL,
    expected_away_score FLOAT NOT NULL,
    home_initialization TEXT NOT NULL,
    away_initialization TEXT NOT NULL,
    home_attack_xg_last5 FLOAT NULL,
    away_attack_xg_last5 FLOAT NULL,
    home_defense_xga_last5 FLOAT NULL,
    away_defense_xga_last5 FLOAT NULL,
    home_attack_xg_last10 FLOAT NULL,
    away_attack_xg_last10 FLOAT NULL,
    home_defense_xga_last10 FLOAT NULL,
    away_defense_xga_last10 FLOAT NULL,
    home_attack_minus_away_defense_last5 FLOAT NULL,
    away_attack_minus_home_defense_last5 FLOAT NULL,
    home_attack_minus_away_defense_last10 FLOAT NULL,
    away_attack_minus_home_defense_last10 FLOAT NULL,
    style_xg_pressure_diff_last5 FLOAT NULL,
    style_xg_pressure_diff_last10 FLOAT NULL,
    home_style_prior_matches INTEGER NOT NULL,
    away_style_prior_matches INTEGER NOT NULL,
    CHECK (home_team <> away_team),
    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0),
    CHECK (home_win IN (0, 1)),
    CHECK (is_draw IN (0, 1)),
    CHECK (away_win IN (0, 1)),
    CHECK (expected_home_score >= 0 AND expected_home_score <= 1),
    CHECK (expected_away_score >= 0 AND expected_away_score <= 1),
    CHECK (home_style_prior_matches >= 0),
    CHECK (away_style_prior_matches >= 0)
);

CREATE TABLE IF NOT EXISTS standings_before_match_v3 (
    match_id INTEGER NOT NULL REFERENCES historical_matches(match_id),
    season TEXT NOT NULL,
    match_date DATE NOT NULL,
    team_name TEXT NOT NULL,
    opponent_team TEXT NOT NULL,
    venue TEXT NOT NULL,
    is_home INTEGER NOT NULL,
    games_played_before INTEGER NOT NULL,
    wins_before INTEGER NOT NULL,
    draws_before INTEGER NOT NULL,
    losses_before INTEGER NOT NULL,
    points_before INTEGER NOT NULL,
    goals_for_before INTEGER NOT NULL,
    goals_against_before INTEGER NOT NULL,
    goal_diff_before INTEGER NOT NULL,
    ppg_before FLOAT NULL,
    rank_before INTEGER NOT NULL,
    points_to_1st_before INTEGER NOT NULL,
    points_to_4th_before INTEGER NOT NULL,
    points_to_6th_before INTEGER NOT NULL,
    points_above_18th_before INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (match_id, team_name),
    CHECK (team_name <> opponent_team),
    CHECK (venue IN ('home', 'away')),
    CHECK (is_home IN (0, 1)),
    CHECK (games_played_before >= 0),
    CHECK (wins_before >= 0),
    CHECK (draws_before >= 0),
    CHECK (losses_before >= 0),
    CHECK (points_before = wins_before * 3 + draws_before),
    CHECK (games_played_before = wins_before + draws_before + losses_before),
    CHECK (goals_for_before >= 0),
    CHECK (goals_against_before >= 0),
    CHECK (goal_diff_before = goals_for_before - goals_against_before),
    CHECK (
        (games_played_before = 0 AND ppg_before IS NULL)
        OR (games_played_before > 0 AND ppg_before >= 0)
    ),
    CHECK (rank_before BETWEEN 1 AND 20)
);

CREATE TABLE IF NOT EXISTS match_features_v3_pressure_experiment (
    match_id INTEGER PRIMARY KEY REFERENCES historical_matches(match_id),
    season_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    home_win INTEGER NOT NULL,
    is_draw INTEGER NOT NULL,
    away_win INTEGER NOT NULL,
    home_home_matches_last5 INTEGER NOT NULL,
    away_away_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last5 INTEGER NOT NULL,
    away_overall_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last10 INTEGER NOT NULL,
    away_overall_matches_last10 INTEGER NOT NULL,
    home_goals_scored_home_last5 FLOAT NULL,
    home_goals_conceded_home_last5 FLOAT NULL,
    home_clean_sheet_rate_home_last5 FLOAT NULL,
    away_goals_scored_away_last5 FLOAT NULL,
    away_goals_conceded_away_last5 FLOAT NULL,
    away_clean_sheet_rate_away_last5 FLOAT NULL,
    home_xg_home_last5 FLOAT NULL,
    home_xga_home_last5 FLOAT NULL,
    away_xg_away_last5 FLOAT NULL,
    away_xga_away_last5 FLOAT NULL,
    home_points_overall_last5 FLOAT NULL,
    away_points_overall_last5 FLOAT NULL,
    home_points_overall_last10 FLOAT NULL,
    away_points_overall_last10 FLOAT NULL,
    home_goal_diff_overall_last5 FLOAT NULL,
    away_goal_diff_overall_last5 FLOAT NULL,
    home_xg_overall_last5 FLOAT NULL,
    home_xga_overall_last5 FLOAT NULL,
    away_xg_overall_last5 FLOAT NULL,
    away_xga_overall_last5 FLOAT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    home_elo_before FLOAT NOT NULL,
    away_elo_before FLOAT NOT NULL,
    elo_diff_before FLOAT NOT NULL,
    elo_diff_home_adjusted FLOAT NOT NULL,
    expected_home_score FLOAT NOT NULL,
    expected_away_score FLOAT NOT NULL,
    home_initialization TEXT NOT NULL,
    away_initialization TEXT NOT NULL,
    home_games_played_before INTEGER NOT NULL,
    away_games_played_before INTEGER NOT NULL,
    home_points_before INTEGER NOT NULL,
    away_points_before INTEGER NOT NULL,
    home_ppg_before FLOAT NULL,
    away_ppg_before FLOAT NULL,
    home_rank_before INTEGER NOT NULL,
    away_rank_before INTEGER NOT NULL,
    home_goal_diff_before INTEGER NOT NULL,
    away_goal_diff_before INTEGER NOT NULL,
    rank_diff_before INTEGER NOT NULL,
    points_diff_before INTEGER NOT NULL,
    ppg_diff_before FLOAT NULL,
    goal_diff_table_diff_before INTEGER NOT NULL,
    home_title_pressure_before FLOAT NULL,
    away_title_pressure_before FLOAT NULL,
    home_top4_pressure_before FLOAT NULL,
    away_top4_pressure_before FLOAT NULL,
    home_top6_pressure_before FLOAT NULL,
    away_top6_pressure_before FLOAT NULL,
    home_relegation_pressure_before FLOAT NULL,
    away_relegation_pressure_before FLOAT NULL,
    home_pressure_index_before FLOAT NULL,
    away_pressure_index_before FLOAT NULL,
    match_pressure_index_before FLOAT NULL,
    pressure_diff_before FLOAT NULL,
    season_progress_before FLOAT NOT NULL,
    CHECK (home_team <> away_team),
    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0),
    CHECK (home_win IN (0, 1)),
    CHECK (is_draw IN (0, 1)),
    CHECK (away_win IN (0, 1)),
    CHECK (expected_home_score >= 0 AND expected_home_score <= 1),
    CHECK (expected_away_score >= 0 AND expected_away_score <= 1),
    CHECK (home_games_played_before >= 0),
    CHECK (away_games_played_before >= 0),
    CHECK (home_points_before >= 0),
    CHECK (away_points_before >= 0),
    CHECK (home_rank_before BETWEEN 1 AND 20),
    CHECK (away_rank_before BETWEEN 1 AND 20),
    CHECK (home_ppg_before IS NULL OR home_ppg_before >= 0),
    CHECK (away_ppg_before IS NULL OR away_ppg_before >= 0),
    CHECK (home_title_pressure_before IS NULL OR home_title_pressure_before BETWEEN 0 AND 1),
    CHECK (away_title_pressure_before IS NULL OR away_title_pressure_before BETWEEN 0 AND 1),
    CHECK (home_top4_pressure_before IS NULL OR home_top4_pressure_before BETWEEN 0 AND 1),
    CHECK (away_top4_pressure_before IS NULL OR away_top4_pressure_before BETWEEN 0 AND 1),
    CHECK (home_top6_pressure_before IS NULL OR home_top6_pressure_before BETWEEN 0 AND 1),
    CHECK (away_top6_pressure_before IS NULL OR away_top6_pressure_before BETWEEN 0 AND 1),
    CHECK (home_relegation_pressure_before IS NULL OR home_relegation_pressure_before BETWEEN 0 AND 1),
    CHECK (away_relegation_pressure_before IS NULL OR away_relegation_pressure_before BETWEEN 0 AND 1),
    CHECK (home_pressure_index_before IS NULL OR home_pressure_index_before BETWEEN 0 AND 1),
    CHECK (away_pressure_index_before IS NULL OR away_pressure_index_before BETWEEN 0 AND 1),
    CHECK (match_pressure_index_before IS NULL OR match_pressure_index_before BETWEEN 0 AND 1),
    CHECK (season_progress_before BETWEEN 0 AND 1)
);

CREATE TABLE IF NOT EXISTS match_features_v3_h2h_experiment (
    match_id INTEGER PRIMARY KEY REFERENCES historical_matches(match_id),
    season_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    home_win INTEGER NOT NULL,
    is_draw INTEGER NOT NULL,
    away_win INTEGER NOT NULL,
    home_home_matches_last5 INTEGER NOT NULL,
    away_away_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last5 INTEGER NOT NULL,
    away_overall_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last10 INTEGER NOT NULL,
    away_overall_matches_last10 INTEGER NOT NULL,
    home_goals_scored_home_last5 FLOAT NULL,
    home_goals_conceded_home_last5 FLOAT NULL,
    home_clean_sheet_rate_home_last5 FLOAT NULL,
    away_goals_scored_away_last5 FLOAT NULL,
    away_goals_conceded_away_last5 FLOAT NULL,
    away_clean_sheet_rate_away_last5 FLOAT NULL,
    home_xg_home_last5 FLOAT NULL,
    home_xga_home_last5 FLOAT NULL,
    away_xg_away_last5 FLOAT NULL,
    away_xga_away_last5 FLOAT NULL,
    home_points_overall_last5 FLOAT NULL,
    away_points_overall_last5 FLOAT NULL,
    home_points_overall_last10 FLOAT NULL,
    away_points_overall_last10 FLOAT NULL,
    home_goal_diff_overall_last5 FLOAT NULL,
    away_goal_diff_overall_last5 FLOAT NULL,
    home_xg_overall_last5 FLOAT NULL,
    home_xga_overall_last5 FLOAT NULL,
    away_xg_overall_last5 FLOAT NULL,
    away_xga_overall_last5 FLOAT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    home_elo_before FLOAT NOT NULL,
    away_elo_before FLOAT NOT NULL,
    elo_diff_before FLOAT NOT NULL,
    elo_diff_home_adjusted FLOAT NOT NULL,
    expected_home_score FLOAT NOT NULL,
    expected_away_score FLOAT NOT NULL,
    home_initialization TEXT NOT NULL,
    away_initialization TEXT NOT NULL,
    h2h_matches_prior INTEGER NOT NULL,
    h2h_home_wins_prior INTEGER NOT NULL,
    h2h_draws_prior INTEGER NOT NULL,
    h2h_away_wins_prior INTEGER NOT NULL,
    h2h_home_goals_avg_prior FLOAT NULL,
    h2h_away_goals_avg_prior FLOAT NULL,
    h2h_home_points_avg_prior FLOAT NULL,
    h2h_away_points_avg_prior FLOAT NULL,
    h2h_goal_diff_avg_prior FLOAT NULL,
    h2h_home_win_rate_prior FLOAT NULL,
    h2h_draw_rate_prior FLOAT NULL,
    h2h_away_win_rate_prior FLOAT NULL,
    h2h_last_meeting_days INTEGER NULL,
    h2h_last_meeting_home_goals INTEGER NULL,
    h2h_last_meeting_away_goals INTEGER NULL,
    h2h_last_meeting_result TEXT NULL,
    CHECK (home_team <> away_team),
    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0),
    CHECK (home_win IN (0, 1)),
    CHECK (is_draw IN (0, 1)),
    CHECK (away_win IN (0, 1)),
    CHECK (expected_home_score >= 0 AND expected_home_score <= 1),
    CHECK (expected_away_score >= 0 AND expected_away_score <= 1),
    CHECK (h2h_matches_prior >= 0),
    CHECK (h2h_home_wins_prior >= 0),
    CHECK (h2h_draws_prior >= 0),
    CHECK (h2h_away_wins_prior >= 0),
    CHECK (h2h_last_meeting_days IS NULL OR h2h_last_meeting_days > 0),
    CHECK (h2h_last_meeting_result IS NULL OR h2h_last_meeting_result IN ('H', 'D', 'A'))
);

CREATE TABLE IF NOT EXISTS production_ingestion_runs (
    run_id SERIAL PRIMARY KEY,
    run_started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    run_finished_at TIMESTAMP NULL,
    run_status TEXT NOT NULL,
    run_type TEXT NOT NULL,
    target_season TEXT NOT NULL,
    target_gameweek INTEGER NULL,
    deadline_time TIMESTAMP NULL,
    fpl_bootstrap_status TEXT NULL,
    fpl_fixtures_status TEXT NULL,
    football_data_status TEXT NULL,
    understat_status TEXT NULL,
    rows_fpl_players INTEGER NOT NULL DEFAULT 0,
    rows_fpl_fixtures INTEGER NOT NULL DEFAULT 0,
    rows_new_results INTEGER NOT NULL DEFAULT 0,
    rows_new_xg INTEGER NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (run_status IN ('started', 'success', 'partial', 'failed')),
    CHECK (target_gameweek IS NULL OR target_gameweek > 0),
    CHECK (rows_fpl_players >= 0),
    CHECK (rows_fpl_fixtures >= 0),
    CHECK (rows_new_results >= 0),
    CHECK (rows_new_xg >= 0)
);

CREATE TABLE IF NOT EXISTS production_fpl_bootstrap_snapshots (
    snapshot_id BIGSERIAL PRIMARY KEY,
    run_id INTEGER NOT NULL REFERENCES production_ingestion_runs(run_id),
    snapshot_time TIMESTAMP NOT NULL,
    event_id INTEGER NULL,
    deadline_time TIMESTAMP NULL,
    player_id INTEGER NOT NULL,
    player_name TEXT NOT NULL,
    web_name TEXT NOT NULL,
    team_id INTEGER NOT NULL,
    team_name TEXT NULL,
    position_id INTEGER NOT NULL,
    now_cost INTEGER NOT NULL,
    selected_by_percent FLOAT NULL,
    total_points INTEGER NOT NULL,
    form FLOAT NULL,
    status TEXT NOT NULL,
    chance_of_playing_next_round INTEGER NULL,
    chance_of_playing_this_round INTEGER NULL,
    news TEXT NULL,
    news_added TIMESTAMP NULL,
    raw_player_json JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_fpl_fixture_snapshots (
    snapshot_id BIGSERIAL PRIMARY KEY,
    run_id INTEGER NOT NULL REFERENCES production_ingestion_runs(run_id),
    snapshot_time TIMESTAMP NOT NULL,
    event_id INTEGER NULL,
    fixture_id INTEGER NOT NULL,
    kickoff_time TIMESTAMP NULL,
    team_h_id INTEGER NOT NULL,
    team_a_id INTEGER NOT NULL,
    team_h_name TEXT NULL,
    team_a_name TEXT NULL,
    finished BOOLEAN NOT NULL,
    started BOOLEAN NOT NULL,
    finished_provisional BOOLEAN NULL,
    team_h_score INTEGER NULL,
    team_a_score INTEGER NULL,
    raw_fixture_json JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_football_data_match_staging (
    staging_id BIGSERIAL PRIMARY KEY,
    run_id INTEGER NOT NULL REFERENCES production_ingestion_runs(run_id),
    source_name TEXT NOT NULL,
    target_season TEXT NOT NULL,
    source_url TEXT NOT NULL,
    source_file_name TEXT NOT NULL,
    match_date DATE NOT NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    raw_row_json JSONB NOT NULL,
    validation_status TEXT NOT NULL,
    validation_error TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (home_team <> away_team),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0),
    CHECK (result IN ('H', 'D', 'A'))
);

CREATE TABLE IF NOT EXISTS production_understat_xg_staging (
    staging_id BIGSERIAL PRIMARY KEY,
    run_id INTEGER NOT NULL REFERENCES production_ingestion_runs(run_id),
    source_name TEXT NOT NULL,
    target_season TEXT NOT NULL,
    match_date DATE NOT NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_xg FLOAT NOT NULL,
    away_xg FLOAT NOT NULL,
    raw_row_json JSONB NOT NULL,
    validation_status TEXT NOT NULL,
    validation_error TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (home_team <> away_team),
    CHECK (home_xg >= 0),
    CHECK (away_xg >= 0)
);

CREATE TABLE IF NOT EXISTS production_data_freshness (
    source_name TEXT PRIMARY KEY,
    last_successful_run_id INTEGER NULL REFERENCES production_ingestion_runs(run_id),
    last_successful_update_at TIMESTAMP NULL,
    latest_event_id INTEGER NULL,
    latest_deadline_time TIMESTAMP NULL,
    latest_completed_match_date DATE NULL,
    latest_error_message TEXT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_prediction_runs (
    prediction_run_id SERIAL PRIMARY KEY,
    run_started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    run_finished_at TIMESTAMP NULL,
    run_status TEXT NOT NULL,
    target_season TEXT NOT NULL,
    target_gameweek INTEGER NULL,
    prediction_mode TEXT NOT NULL,
    model_name TEXT NOT NULL,
    model_artifact_path TEXT NOT NULL,
    feature_artifact_path TEXT NOT NULL,
    draw_threshold FLOAT NOT NULL,
    source_feature_table TEXT NOT NULL,
    rows_loaded INTEGER NOT NULL DEFAULT 0,
    rows_predicted INTEGER NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (run_status IN ('started', 'success', 'skipped', 'failed')),
    CHECK (prediction_mode IN ('upcoming', 'historical_replay', 'dry_run')),
    CHECK (target_gameweek IS NULL OR target_gameweek > 0),
    CHECK (draw_threshold >= 0 AND draw_threshold <= 1),
    CHECK (rows_loaded >= 0),
    CHECK (rows_predicted >= 0)
);

CREATE TABLE IF NOT EXISTS production_match_predictions (
    prediction_id BIGSERIAL PRIMARY KEY,
    prediction_run_id INTEGER NOT NULL REFERENCES production_prediction_runs(prediction_run_id),
    target_season TEXT NOT NULL,
    target_gameweek INTEGER NULL,
    match_id INTEGER NULL,
    fixture_id INTEGER NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    prob_home_win FLOAT NOT NULL,
    prob_draw FLOAT NOT NULL,
    prob_away_win FLOAT NOT NULL,
    argmax_prediction TEXT NOT NULL,
    overlay_prediction TEXT NOT NULL,
    draw_overlay_applied BOOLEAN NOT NULL,
    draw_risk_flag BOOLEAN NOT NULL,
    confidence FLOAT NOT NULL,
    model_name TEXT NOT NULL,
    feature_source TEXT NOT NULL,
    prediction_created_at TIMESTAMP NOT NULL,
    actual_result TEXT NULL,
    was_correct_argmax BOOLEAN NULL,
    was_correct_overlay BOOLEAN NULL,
    scored_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (home_team <> away_team),
    CHECK (target_gameweek IS NULL OR target_gameweek > 0),
    CHECK (prob_home_win >= 0 AND prob_home_win <= 1),
    CHECK (prob_draw >= 0 AND prob_draw <= 1),
    CHECK (prob_away_win >= 0 AND prob_away_win <= 1),
    CHECK (ABS((prob_home_win + prob_draw + prob_away_win) - 1.0) <= 0.000001),
    CHECK (argmax_prediction IN ('H', 'D', 'A')),
    CHECK (overlay_prediction IN ('H', 'D', 'A')),
    CHECK (actual_result IS NULL OR actual_result IN ('H', 'D', 'A')),
    CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE TABLE IF NOT EXISTS production_model_health_log (
    health_log_id BIGSERIAL PRIMARY KEY,
    computed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    target_season TEXT NOT NULL,
    target_gameweek INTEGER NULL,
    model_name TEXT NOT NULL,
    prediction_count INTEGER NOT NULL DEFAULT 0,
    scored_count INTEGER NOT NULL DEFAULT 0,
    accuracy_argmax FLOAT NULL,
    accuracy_overlay FLOAT NULL,
    log_loss FLOAT NULL,
    brier FLOAT NULL,
    draw_recall_argmax FLOAT NULL,
    draw_precision_argmax FLOAT NULL,
    draw_f1_argmax FLOAT NULL,
    draw_recall_overlay FLOAT NULL,
    draw_precision_overlay FLOAT NULL,
    draw_f1_overlay FLOAT NULL,
    home_pred_rate_argmax FLOAT NULL,
    draw_pred_rate_argmax FLOAT NULL,
    away_pred_rate_argmax FLOAT NULL,
    home_actual_rate FLOAT NULL,
    draw_actual_rate FLOAT NULL,
    away_actual_rate FLOAT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (target_gameweek IS NULL OR target_gameweek > 0),
    CHECK (prediction_count >= 0),
    CHECK (scored_count >= 0),
    CHECK (accuracy_argmax IS NULL OR (accuracy_argmax >= 0 AND accuracy_argmax <= 1)),
    CHECK (accuracy_overlay IS NULL OR (accuracy_overlay >= 0 AND accuracy_overlay <= 1)),
    CHECK (log_loss IS NULL OR log_loss >= 0),
    CHECK (brier IS NULL OR brier >= 0),
    CHECK (draw_recall_argmax IS NULL OR (draw_recall_argmax >= 0 AND draw_recall_argmax <= 1)),
    CHECK (draw_precision_argmax IS NULL OR (draw_precision_argmax >= 0 AND draw_precision_argmax <= 1)),
    CHECK (draw_f1_argmax IS NULL OR (draw_f1_argmax >= 0 AND draw_f1_argmax <= 1)),
    CHECK (draw_recall_overlay IS NULL OR (draw_recall_overlay >= 0 AND draw_recall_overlay <= 1)),
    CHECK (draw_precision_overlay IS NULL OR (draw_precision_overlay >= 0 AND draw_precision_overlay <= 1)),
    CHECK (draw_f1_overlay IS NULL OR (draw_f1_overlay >= 0 AND draw_f1_overlay <= 1)),
    CHECK (home_pred_rate_argmax IS NULL OR (home_pred_rate_argmax >= 0 AND home_pred_rate_argmax <= 1)),
    CHECK (draw_pred_rate_argmax IS NULL OR (draw_pred_rate_argmax >= 0 AND draw_pred_rate_argmax <= 1)),
    CHECK (away_pred_rate_argmax IS NULL OR (away_pred_rate_argmax >= 0 AND away_pred_rate_argmax <= 1)),
    CHECK (home_actual_rate IS NULL OR (home_actual_rate >= 0 AND home_actual_rate <= 1)),
    CHECK (draw_actual_rate IS NULL OR (draw_actual_rate >= 0 AND draw_actual_rate <= 1)),
    CHECK (away_actual_rate IS NULL OR (away_actual_rate >= 0 AND away_actual_rate <= 1))
);

CREATE TABLE IF NOT EXISTS production_team_name_mapping (
    fpl_team_id INTEGER PRIMARY KEY,
    fpl_team_name TEXT NOT NULL,
    model_team_name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    source TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS production_upcoming_match_features_v3 (
    upcoming_feature_id BIGSERIAL PRIMARY KEY,
    target_season TEXT NOT NULL,
    target_gameweek INTEGER NULL,
    fixture_id INTEGER NOT NULL,
    kickoff_time TIMESTAMP NOT NULL,
    match_date DATE NOT NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_home_matches_last5 INTEGER NULL,
    away_away_matches_last5 INTEGER NULL,
    home_overall_matches_last5 INTEGER NULL,
    away_overall_matches_last5 INTEGER NULL,
    home_overall_matches_last10 INTEGER NULL,
    away_overall_matches_last10 INTEGER NULL,
    home_goals_scored_home_last5 FLOAT NULL,
    home_goals_conceded_home_last5 FLOAT NULL,
    home_clean_sheet_rate_home_last5 FLOAT NULL,
    away_goals_scored_away_last5 FLOAT NULL,
    away_goals_conceded_away_last5 FLOAT NULL,
    away_clean_sheet_rate_away_last5 FLOAT NULL,
    home_xg_home_last5 FLOAT NULL,
    home_xga_home_last5 FLOAT NULL,
    away_xg_away_last5 FLOAT NULL,
    away_xga_away_last5 FLOAT NULL,
    home_points_overall_last5 FLOAT NULL,
    away_points_overall_last5 FLOAT NULL,
    home_points_overall_last10 FLOAT NULL,
    away_points_overall_last10 FLOAT NULL,
    home_goal_diff_overall_last5 FLOAT NULL,
    away_goal_diff_overall_last5 FLOAT NULL,
    home_xg_overall_last5 FLOAT NULL,
    home_xga_overall_last5 FLOAT NULL,
    away_xg_overall_last5 FLOAT NULL,
    away_xga_overall_last5 FLOAT NULL,
    home_elo_before FLOAT NULL,
    away_elo_before FLOAT NULL,
    elo_diff_before FLOAT NULL,
    elo_diff_home_adjusted FLOAT NULL,
    expected_home_score FLOAT NULL,
    expected_away_score FLOAT NULL,
    feature_generated_at TIMESTAMP NOT NULL,
    source_snapshot_run_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (target_season, fixture_id),
    CHECK (target_gameweek IS NULL OR target_gameweek > 0),
    CHECK (home_team <> away_team)
);

CREATE TABLE IF NOT EXISTS fpl_player_gameweek_history_v3 (
    id SERIAL PRIMARY KEY,
    source TEXT NOT NULL DEFAULT 'vaastav',
    season TEXT NOT NULL,
    gameweek INTEGER NOT NULL,
    player_source_id TEXT NULL,
    player_name TEXT NOT NULL,
    player_slug TEXT NULL,
    team_name TEXT NULL,
    opponent_team_name TEXT NULL,
    fixture_id TEXT NULL,
    kickoff_time TIMESTAMP NULL,
    was_home BOOLEAN NULL,
    position TEXT NULL,
    minutes INTEGER NULL,
    total_points INTEGER NULL,
    goals_scored INTEGER NULL,
    assists INTEGER NULL,
    clean_sheets INTEGER NULL,
    goals_conceded INTEGER NULL,
    own_goals INTEGER NULL,
    penalties_saved INTEGER NULL,
    penalties_missed INTEGER NULL,
    yellow_cards INTEGER NULL,
    red_cards INTEGER NULL,
    saves INTEGER NULL,
    bonus INTEGER NULL,
    bps INTEGER NULL,
    influence FLOAT NULL,
    creativity FLOAT NULL,
    threat FLOAT NULL,
    ict_index FLOAT NULL,
    starts INTEGER NULL,
    expected_goals FLOAT NULL,
    expected_assists FLOAT NULL,
    expected_goal_involvements FLOAT NULL,
    expected_goals_conceded FLOAT NULL,
    transfers_in INTEGER NULL,
    transfers_out INTEGER NULL,
    selected INTEGER NULL,
    value FLOAT NULL,
    raw_player_key TEXT NULL,
    source_file TEXT NOT NULL,
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (gameweek > 0),
    CHECK (TRIM(player_name) <> ''),
    CHECK (TRIM(source_file) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fpl_pgh_v3_unique_fixture_player_id
ON fpl_player_gameweek_history_v3 (
    season,
    gameweek,
    player_source_id,
    fixture_id,
    source_file
)
WHERE fixture_id IS NOT NULL AND player_source_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_fpl_pgh_v3_unique_fixture_name
ON fpl_player_gameweek_history_v3 (
    season,
    gameweek,
    player_name,
    fixture_id,
    source_file
)
WHERE fixture_id IS NOT NULL AND player_source_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_fpl_pgh_v3_unique_no_fixture_player_id
ON fpl_player_gameweek_history_v3 (
    season,
    gameweek,
    player_source_id,
    source_file
)
WHERE fixture_id IS NULL AND player_source_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_fpl_pgh_v3_unique_no_fixture_name
ON fpl_player_gameweek_history_v3 (
    season,
    gameweek,
    player_name,
    source_file
)
WHERE fixture_id IS NULL AND player_source_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_fpl_pgh_v3_season
ON fpl_player_gameweek_history_v3 (season);

CREATE INDEX IF NOT EXISTS idx_fpl_pgh_v3_gameweek
ON fpl_player_gameweek_history_v3 (gameweek);

CREATE INDEX IF NOT EXISTS idx_fpl_pgh_v3_player_name
ON fpl_player_gameweek_history_v3 (player_name);

CREATE INDEX IF NOT EXISTS idx_fpl_pgh_v3_team_name
ON fpl_player_gameweek_history_v3 (team_name);

CREATE INDEX IF NOT EXISTS idx_fpl_pgh_v3_position
ON fpl_player_gameweek_history_v3 (position);

CREATE TABLE IF NOT EXISTS fpl_player_features_v3 (
    feature_id BIGSERIAL PRIMARY KEY,
    canonical_player_key TEXT NOT NULL,
    fpl_code INTEGER NOT NULL,
    season TEXT NOT NULL,
    gameweek INTEGER NOT NULL,
    player_name TEXT NOT NULL,
    player_source_id TEXT NOT NULL,
    target_total_points INTEGER NULL,
    prior_points_last1 FLOAT NULL,
    prior_points_last3 FLOAT NULL,
    prior_points_last5 FLOAT NULL,
    prior_points_last10 FLOAT NULL,
    prior_points_season FLOAT NULL,
    prior_minutes_last3 FLOAT NULL,
    prior_minutes_last5 FLOAT NULL,
    prior_minutes_last10 FLOAT NULL,
    prior_appearances_last5 FLOAT NULL,
    prior_starts_last5 FLOAT NULL,
    prior_goals_last5 FLOAT NULL,
    prior_assists_last5 FLOAT NULL,
    prior_bonus_last5 FLOAT NULL,
    prior_clean_sheets_last5 FLOAT NULL,
    prior_saves_last5 FLOAT NULL,
    prior_xg_last5 FLOAT NULL,
    prior_xa_last5 FLOAT NULL,
    prior_points_per_90 FLOAT NULL,
    prior_minutes_total FLOAT NULL,
    prior_gameweeks_played FLOAT NULL,
    feature_history_start_season TEXT NULL,
    feature_history_start_gameweek INTEGER NULL,
    feature_history_end_season TEXT NULL,
    feature_history_end_gameweek INTEGER NULL,
    prior_history_row_count INTEGER NOT NULL DEFAULT 0,
    source_history_row_id INTEGER NOT NULL REFERENCES fpl_player_gameweek_history_v3(id),
    source_history_row_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (canonical_player_key, season, gameweek),
    CHECK (gameweek > 0),
    CHECK (feature_history_start_gameweek IS NULL OR feature_history_start_gameweek > 0),
    CHECK (feature_history_end_gameweek IS NULL OR feature_history_end_gameweek > 0),
    CHECK (prior_history_row_count >= 0),
    CHECK (source_history_row_count > 0),
    CHECK (TRIM(canonical_player_key) <> ''),
    CHECK (TRIM(season) <> ''),
    CHECK (TRIM(player_name) <> ''),
    CHECK (TRIM(player_source_id) <> '')
);

CREATE INDEX IF NOT EXISTS idx_fpl_player_features_v3_season_gw
ON fpl_player_features_v3 (season, gameweek);

CREATE INDEX IF NOT EXISTS idx_fpl_player_features_v3_player_key
ON fpl_player_features_v3 (canonical_player_key);

CREATE INDEX IF NOT EXISTS idx_fpl_player_features_v3_fpl_code
ON fpl_player_features_v3 (fpl_code);

CREATE INDEX IF NOT EXISTS idx_fpl_player_features_v3_source_history
ON fpl_player_features_v3 (source_history_row_id);

CREATE TABLE IF NOT EXISTS fpl_model_training_runs_v3 (
    training_run_id BIGSERIAL PRIMARY KEY,
    run_started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    run_finished_at TIMESTAMP NULL,
    run_status TEXT NOT NULL,
    model_name TEXT NOT NULL,
    train_seasons TEXT[] NULL,
    validation_season TEXT NULL,
    final_holdout_season TEXT NULL,
    feature_table TEXT NULL,
    row_count INTEGER NOT NULL DEFAULT 0,
    metrics_json JSONB NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (run_status IN ('started', 'success', 'failed', 'skipped')),
    CHECK (row_count >= 0)
);

CREATE TABLE IF NOT EXISTS fpl_player_predictions_v3 (
    prediction_id BIGSERIAL PRIMARY KEY,
    target_season TEXT NOT NULL,
    target_gameweek INTEGER NOT NULL,
    player_id INTEGER NOT NULL,
    fpl_code INTEGER NULL,
    player_name TEXT NOT NULL,
    team_id INTEGER NOT NULL,
    team_name TEXT NULL,
    position_id INTEGER NOT NULL,
    now_cost INTEGER NOT NULL,
    predicted_points FLOAT NOT NULL,
    availability_factor FLOAT NOT NULL,
    expected_points FLOAT NOT NULL,
    status TEXT NOT NULL,
    chance_of_playing INTEGER NULL,
    source_feature_season TEXT NULL,
    source_feature_gameweek INTEGER NULL,
    source_bootstrap_run_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (target_season, target_gameweek, player_id),
    CHECK (target_gameweek > 0),
    CHECK (position_id IN (1, 2, 3, 4)),
    CHECK (now_cost >= 0),
    CHECK (availability_factor >= 0 AND availability_factor <= 1),
    CHECK (expected_points >= 0)
);

CREATE INDEX IF NOT EXISTS idx_fpl_predictions_v3_target
ON fpl_player_predictions_v3 (target_season, target_gameweek);

CREATE TABLE IF NOT EXISTS fpl_optimizer_outputs_v3 (
    optimizer_output_id BIGSERIAL PRIMARY KEY,
    target_season TEXT NOT NULL,
    target_gameweek INTEGER NOT NULL,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    budget_limit INTEGER NOT NULL,
    squad_cost INTEGER NOT NULL,
    squad_json JSONB NOT NULL,
    starting_xi_json JSONB NOT NULL,
    captain_player_id INTEGER NOT NULL,
    vice_captain_player_id INTEGER NOT NULL,
    objective_value FLOAT NOT NULL,
    source_prediction_count INTEGER NOT NULL,
    UNIQUE (target_season, target_gameweek),
    CHECK (target_gameweek > 0),
    CHECK (budget_limit >= 0),
    CHECK (squad_cost >= 0),
    CHECK (source_prediction_count > 0)
);

CREATE INDEX IF NOT EXISTS idx_fpl_optimizer_outputs_v3_target
ON fpl_optimizer_outputs_v3 (target_season, target_gameweek);

CREATE TABLE IF NOT EXISTS production_fpl_gameweek_snapshots_v3 (
    snapshot_id BIGSERIAL PRIMARY KEY,
    ingestion_run_id INTEGER NULL REFERENCES production_ingestion_runs(run_id),
    target_season TEXT NOT NULL,
    gameweek INTEGER NOT NULL,
    snapshot_time TIMESTAMP NOT NULL,
    player_id INTEGER NOT NULL,
    fpl_code INTEGER NULL,
    player_name TEXT NOT NULL,
    team_id INTEGER NULL,
    position_id INTEGER NULL,
    minutes INTEGER NOT NULL DEFAULT 0,
    total_points INTEGER NOT NULL DEFAULT 0,
    goals_scored INTEGER NOT NULL DEFAULT 0,
    assists INTEGER NOT NULL DEFAULT 0,
    clean_sheets INTEGER NOT NULL DEFAULT 0,
    saves INTEGER NOT NULL DEFAULT 0,
    bonus INTEGER NOT NULL DEFAULT 0,
    starts INTEGER NOT NULL DEFAULT 0,
    expected_goals FLOAT NULL,
    expected_assists FLOAT NULL,
    expected_goal_involvements FLOAT NULL,
    expected_goals_conceded FLOAT NULL,
    identity_status TEXT NOT NULL,
    raw_stats_json JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (target_season, gameweek, player_id),
    CHECK (gameweek > 0),
    CHECK (minutes >= 0),
    CHECK (identity_status IN ('matched', 'unmatched'))
);

CREATE INDEX IF NOT EXISTS idx_production_fpl_gameweek_v3_target
ON production_fpl_gameweek_snapshots_v3 (target_season, gameweek);

CREATE INDEX IF NOT EXISTS idx_production_fpl_gameweek_v3_fpl_code
ON production_fpl_gameweek_snapshots_v3 (fpl_code);

-- Phase 1D: FPL player identity map (expanded schema).
-- Maps each season's FPL element ID (season-local) to the globally stable
-- fpl_code obtained exclusively from players_raw.csv via exact join on
--   (season, player_source_id) = (season, id in players_raw.csv).
-- fpl_code is the canonical cross-season identity key ONLY when
-- mapping_method = 'element_id_exact'.
-- Unmatched rows have fpl_code NULL and needs_manual_review = TRUE.

CREATE TABLE IF NOT EXISTS fpl_player_identity_map_v3 (
    identity_id BIGSERIAL PRIMARY KEY,
    canonical_player_key TEXT NULL,
    fpl_code INTEGER NULL,
    season TEXT NOT NULL,
    player_source_id TEXT NOT NULL,
    player_name TEXT NOT NULL,
    normalized_player_name TEXT NOT NULL,
    team_name TEXT NULL,
    position TEXT NULL,
    first_gameweek INTEGER NULL,
    last_gameweek INTEGER NULL,
    row_count INTEGER NOT NULL DEFAULT 0,
    minutes_total INTEGER NULL,
    total_points_sum INTEGER NULL,
    history_rows_matched INTEGER NOT NULL DEFAULT 0,
    mapping_method TEXT NOT NULL,
    confidence_score FLOAT NOT NULL DEFAULT 0.0,
    needs_manual_review BOOLEAN NOT NULL DEFAULT FALSE,
    review_reason TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (season, player_source_id),
    CHECK (confidence_score >= 0 AND confidence_score <= 1),
    CHECK (mapping_method IN ('element_id_exact', 'unmatched')),
    CHECK (row_count >= 0),
    CHECK (history_rows_matched >= 0),
    CHECK (TRIM(season) <> ''),
    CHECK (TRIM(player_source_id) <> ''),
    CHECK (TRIM(player_name) <> ''),
    CHECK (TRIM(normalized_player_name) <> '')
);

CREATE INDEX IF NOT EXISTS idx_fpl_identity_map_v3_fpl_code
ON fpl_player_identity_map_v3 (fpl_code)
WHERE fpl_code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_fpl_identity_map_v3_season
ON fpl_player_identity_map_v3 (season);

CREATE INDEX IF NOT EXISTS idx_fpl_identity_map_v3_needs_review
ON fpl_player_identity_map_v3 (needs_manual_review)
WHERE needs_manual_review = TRUE;

CREATE INDEX IF NOT EXISTS idx_fpl_identity_map_v3_canonical_key
ON fpl_player_identity_map_v3 (canonical_player_key)
WHERE canonical_player_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_fpl_identity_map_v3_season_player
ON fpl_player_identity_map_v3 (season, player_source_id);
