-- Tier 3 Phase 1A local historical match ingestion schema.
-- This file intentionally creates only the Phase 1A foundation tables.

CREATE TABLE IF NOT EXISTS seasons (
    season_id TEXT PRIMARY KEY,
    season_name TEXT NOT NULL,
    start_date DATE,
    end_date DATE,
    is_current BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_name_mapping (
    source TEXT NOT NULL,
    source_name TEXT NOT NULL,
    canonical_name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (source, source_name)
);

CREATE TABLE IF NOT EXISTS historical_matches (
    match_id SERIAL PRIMARY KEY,
    season_id TEXT NOT NULL REFERENCES seasons(season_id),
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'football_data',
    source_file TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (season_id, home_team, away_team),
    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_team <> away_team),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0)
);

CREATE TABLE IF NOT EXISTS historical_understat_xg (
    understat_match_id TEXT PRIMARY KEY,
    season_id TEXT NOT NULL REFERENCES seasons(season_id),
    match_date DATE NOT NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_xg FLOAT NOT NULL,
    away_xg FLOAT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    source TEXT NOT NULL DEFAULT 'understat',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (season_id, match_date, home_team, away_team),
    CHECK (home_team <> away_team),
    CHECK (home_xg >= 0),
    CHECK (away_xg >= 0),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0)
);

CREATE TABLE IF NOT EXISTS match_features_v3_base (
    match_id INTEGER PRIMARY KEY REFERENCES historical_matches(match_id),
    season_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    home_win INTEGER NOT NULL,
    is_draw INTEGER NOT NULL,
    away_win INTEGER NOT NULL,
    home_home_matches_last5 INTEGER NOT NULL,
    away_away_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last5 INTEGER NOT NULL,
    away_overall_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last10 INTEGER NOT NULL,
    away_overall_matches_last10 INTEGER NOT NULL,
    home_goals_scored_home_last5 FLOAT NULL,
    home_goals_conceded_home_last5 FLOAT NULL,
    home_clean_sheet_rate_home_last5 FLOAT NULL,
    away_goals_scored_away_last5 FLOAT NULL,
    away_goals_conceded_away_last5 FLOAT NULL,
    away_clean_sheet_rate_away_last5 FLOAT NULL,
    home_xg_home_last5 FLOAT NULL,
    home_xga_home_last5 FLOAT NULL,
    away_xg_away_last5 FLOAT NULL,
    away_xga_away_last5 FLOAT NULL,
    home_points_overall_last5 FLOAT NULL,
    away_points_overall_last5 FLOAT NULL,
    home_points_overall_last10 FLOAT NULL,
    away_points_overall_last10 FLOAT NULL,
    home_goal_diff_overall_last5 FLOAT NULL,
    away_goal_diff_overall_last5 FLOAT NULL,
    home_xg_overall_last5 FLOAT NULL,
    home_xga_overall_last5 FLOAT NULL,
    away_xg_overall_last5 FLOAT NULL,
    away_xga_overall_last5 FLOAT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS elo_ratings_v3 (
    match_id INTEGER PRIMARY KEY REFERENCES historical_matches(match_id),
    season_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    home_elo_before FLOAT NOT NULL,
    away_elo_before FLOAT NOT NULL,
    home_elo_after FLOAT NOT NULL,
    away_elo_after FLOAT NOT NULL,
    home_elo_delta FLOAT NOT NULL,
    away_elo_delta FLOAT NOT NULL,
    elo_diff_before FLOAT NOT NULL,
    elo_diff_home_adjusted FLOAT NOT NULL,
    expected_home_score FLOAT NOT NULL,
    expected_away_score FLOAT NOT NULL,
    actual_home_score FLOAT NOT NULL,
    actual_away_score FLOAT NOT NULL,
    k_factor FLOAT NOT NULL,
    home_advantage FLOAT NOT NULL,
    home_initialization TEXT NOT NULL,
    away_initialization TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (home_team <> away_team),
    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0),
    CHECK (expected_home_score >= 0 AND expected_home_score <= 1),
    CHECK (expected_away_score >= 0 AND expected_away_score <= 1),
    CHECK (actual_home_score IN (0, 0.5, 1)),
    CHECK (actual_away_score IN (0, 0.5, 1))
);

CREATE TABLE IF NOT EXISTS match_features_v3_elo (
    match_id INTEGER PRIMARY KEY REFERENCES historical_matches(match_id),
    season_id TEXT NOT NULL,
    match_date DATE NOT NULL,
    kickoff_time TIMESTAMP NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    home_goals INTEGER NOT NULL,
    away_goals INTEGER NOT NULL,
    result TEXT NOT NULL,
    home_win INTEGER NOT NULL,
    is_draw INTEGER NOT NULL,
    away_win INTEGER NOT NULL,
    home_home_matches_last5 INTEGER NOT NULL,
    away_away_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last5 INTEGER NOT NULL,
    away_overall_matches_last5 INTEGER NOT NULL,
    home_overall_matches_last10 INTEGER NOT NULL,
    away_overall_matches_last10 INTEGER NOT NULL,
    home_goals_scored_home_last5 FLOAT NULL,
    home_goals_conceded_home_last5 FLOAT NULL,
    home_clean_sheet_rate_home_last5 FLOAT NULL,
    away_goals_scored_away_last5 FLOAT NULL,
    away_goals_conceded_away_last5 FLOAT NULL,
    away_clean_sheet_rate_away_last5 FLOAT NULL,
    home_xg_home_last5 FLOAT NULL,
    home_xga_home_last5 FLOAT NULL,
    away_xg_away_last5 FLOAT NULL,
    away_xga_away_last5 FLOAT NULL,
    home_points_overall_last5 FLOAT NULL,
    away_points_overall_last5 FLOAT NULL,
    home_points_overall_last10 FLOAT NULL,
    away_points_overall_last10 FLOAT NULL,
    home_goal_diff_overall_last5 FLOAT NULL,
    away_goal_diff_overall_last5 FLOAT NULL,
    home_xg_overall_last5 FLOAT NULL,
    home_xga_overall_last5 FLOAT NULL,
    away_xg_overall_last5 FLOAT NULL,
    away_xga_overall_last5 FLOAT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    home_elo_before FLOAT NOT NULL,
    away_elo_before FLOAT NOT NULL,
    elo_diff_before FLOAT NOT NULL,
    elo_diff_home_adjusted FLOAT NOT NULL,
    expected_home_score FLOAT NOT NULL,
    expected_away_score FLOAT NOT NULL,
    home_initialization TEXT NOT NULL,
    away_initialization TEXT NOT NULL,
    CHECK (home_team <> away_team),
    CHECK (result IN ('H', 'D', 'A')),
    CHECK (home_goals >= 0),
    CHECK (away_goals >= 0),
    CHECK (home_win IN (0, 1)),
    CHECK (is_draw IN (0, 1)),
    CHECK (away_win IN (0, 1)),
    CHECK (expected_home_score >= 0 AND expected_home_score <= 1),
    CHECK (expected_away_score >= 0 AND expected_away_score <= 1)
);
